import type {
  AppNotification,
  Contract,
  Job,
  Message,
  Milestone,
  Offer,
  Proposal,
  Review,
  SellerProfile,
  Service,
  User,
  VerificationRecord,
} from "@/lib/types";
import { svgGallery, svgImg } from "@/lib/mock-api/placeholder";

export const BUYER_ID = "u-b2";
export const SELLER_ID = "u-1";
export const DEMO_PASSWORD = "demo123";

export const seedUsers: User[] = [
  {
    id: "u-1",
    fullName: "Rustam Qosimov",
    phone: "+998901234567",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-01-10T10:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-2",
    fullName: "Nigora Karimova",
    phone: "+998912345678",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-01-15T11:30:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-3",
    fullName: "Jasur Bekchanov",
    phone: "+998933456789",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-02-01T09:15:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-4",
    fullName: "Zarina Saidova",
    phone: "+998944567890",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-02-12T14:20:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-5",
    fullName: "Umid Aliyev",
    phone: "+998975678901",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-03-01T16:45:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-6",
    fullName: "Shahzod Mirzayev",
    phone: "+998996789012",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-03-10T12:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-7",
    fullName: "Aziza Toshmatova",
    phone: "+998907890123",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-03-18T08:30:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-8",
    fullName: "Bobur Ahmedov",
    phone: "+998918901234",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-04-01T10:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b1",
    fullName: "TechCorp Tashkent MChJ",
    phone: "+998909876543",
    password: DEMO_PASSWORD,
    role: "xaridor",
    createdAt: "2026-01-05T09:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b2",
    fullName: "ArtSoft Studios (Mijoz)",
    phone: "+998918765432",
    password: DEMO_PASSWORD,
    role: "xaridor",
    createdAt: "2026-01-12T14:10:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b3",
    fullName: "Zamona Logistics",
    phone: "+998937654321",
    password: DEMO_PASSWORD,
    role: "xaridor",
    createdAt: "2026-02-20T11:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b4",
    fullName: "Farrux Zokirov",
    phone: "+998946543210",
    password: DEMO_PASSWORD,
    role: "xaridor",
    createdAt: "2026-03-05T15:30:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b5",
    fullName: "Apex Retail Group",
    phone: "+998975432109",
    password: DEMO_PASSWORD,
    role: "xaridor",
    createdAt: "2026-03-25T10:45:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-sus1",
    fullName: "Botir Qobilov",
    phone: "+998901112233",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-04-10T12:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-block1",
    fullName: "CopyMaster_UZ",
    phone: "+998993334455",
    password: DEMO_PASSWORD,
    role: "mutaxassis",
    createdAt: "2026-04-15T09:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
];

export const seedProfiles: Record<string, SellerProfile> = {
  "u-1": {
    userId: "u-1",
    headline: "Senior Fullstack & Next.js Dasturchi",
    bio: "7 yillik tajribaga ega dasturchi. Next.js, React, Node.js, PostgreSQL va murakkab fintech tizimlarni yaratish bo'yicha mutaxassis.",
    location: "Toshkent",
    skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
    categories: ["dasturlash"],
    portfolio: [
      {
        id: "port-1",
        title: "Fintech E-Wallet Web Platformasi",
        description: "To'lovlar va transaksiyalar uchun yuqori yuklamali veb ilova.",
        image: svgImg("port-1", "dasturlash"),
        category: "dasturlash",
      },
      {
        id: "port-2",
        title: "B2B E-Commerce Marketplace",
        description: "Ulgurji savdo uchun avtomatlashtirilgan katalog va ombor boshqaruvi.",
        image: svgImg("port-2", "dasturlash"),
        category: "dasturlash",
      },
    ],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Rus", level: "fluent" },
      { name: "Ingliz", level: "intermediate" },
    ],
    responseTimeHours: 1,
    available: true,
    rating: 4.9,
    completedContracts: 26,
    badge: "top_mutaxassis",
    memberSince: "2026-01-10T10:00:00.000Z",
  },
  "u-2": {
    userId: "u-2",
    headline: "Senior UI/UX Dizayner & Brending Mutaxassisi",
    bio: "Figma, Design System va foydalanuvchi tajribasini (UX) chuqur tushunuvchi dizayner. 50+ dan ortiq muvaffaqiyatli loyihalar.",
    location: "Samarqand",
    skills: ["Figma", "UI/UX", "Mobile Design", "Brand Identity", "Design System"],
    categories: ["dizayn"],
    portfolio: [
      {
        id: "port-3",
        title: "Bank Mobil Ilovasi UI/UX",
        description: "Minimalist va qulay foydalanuvchi interfeysi.",
        image: svgImg("port-3", "dizayn"),
        category: "dizayn",
      },
    ],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Rus", level: "fluent" },
      { name: "Ingliz", level: "fluent" },
    ],
    responseTimeHours: 2,
    available: true,
    rating: 5.0,
    completedContracts: 28,
    badge: "top_mutaxassis",
    memberSince: "2026-01-15T11:30:00.000Z",
  },
  "u-3": {
    userId: "u-3",
    headline: "Telegram Bot & Python Backend Mutaxassisi",
    bio: "Aiogram, FastAPI, PostgreSQL va to'lov tizimlari (Click, Payme) integratsiyalari bo'yicha 4 yillik tajriba.",
    location: "Xorazm",
    skills: ["Python", "Telegram Bot", "FastAPI", "PostgreSQL", "Docker", "Click / Payme"],
    categories: ["dasturlash"],
    portfolio: [
      {
        id: "port-4",
        title: "Yetkazib berish xizmati uchun Telegram Bot",
        description: "Geolokatsiya va onlayn to'lovli avtomatlashtirilgan buyurtma boti.",
        image: svgImg("port-4", "dasturlash"),
        category: "dasturlash",
      },
    ],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Rus", level: "intermediate" },
    ],
    responseTimeHours: 3,
    available: true,
    rating: 4.8,
    completedContracts: 16,
    badge: "ishonchli",
    memberSince: "2026-02-01T09:15:00.000Z",
  },
  "u-4": {
    userId: "u-4",
    headline: "SMM Strateg & Instagram Content Creator",
    bio: "Brendlarni ijtimoiy tarmoqlarda o'stirish, reklama kampaniyalari va kreativ vizual kontent yaratish bo'yicha ekspert.",
    location: "Toshkent",
    skills: ["SMM", "Instagram", "Targeting", "Reels", "Content Strategy"],
    categories: ["marketing"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Rus", level: "fluent" }],
    responseTimeHours: 1,
    available: true,
    rating: 4.7,
    completedContracts: 11,
    badge: "ishonchli",
    memberSince: "2026-02-12T14:20:00.000Z",
  },
  "u-5": {
    userId: "u-5",
    headline: "Flutter & React Native Mobil Dasturchi",
    bio: "iOS va Android uchun bir vaqtda ishlaydigan zamonaviy, tezkor va xavfsiz mobil ilovalar yaratish.",
    location: "Buxoro",
    skills: ["Flutter", "Dart", "React Native", "iOS", "Android", "REST API"],
    categories: ["dasturlash"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Ingliz", level: "fluent" }],
    responseTimeHours: 4,
    available: true,
    rating: 4.9,
    completedContracts: 10,
    badge: "ishonchli",
    memberSince: "2026-03-01T16:45:00.000Z",
  },
  "u-6": {
    userId: "u-6",
    headline: "Professional SEO & Texnik Kopirayter",
    bio: "Saytlar va bizneslar uchun yuqori konversiyali matnlar, maqolalar va texnik hujjatlar yozish.",
    location: "Namangan",
    skills: ["Kopirayting", "SEO", "Texnik matnlar", "Blog"],
    categories: ["kontent"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Rus", level: "fluent" }],
    responseTimeHours: 2,
    available: true,
    rating: 4.8,
    completedContracts: 8,
    badge: "ishonchli",
    memberSince: "2026-03-10T12:00:00.000Z",
  },
  "u-7": {
    userId: "u-7",
    headline: "Ingliz va Rus tillari Tarjimoni",
    bio: "Texnik, yuridik va ilmiy matnlarni yuqori aniqlikda tarjima qilish.",
    location: "Farg'ona",
    skills: ["Tarjima", "Ingliz tili", "Rus tili", "Tahrirlash"],
    categories: ["tarjima"],
    portfolio: [],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Ingliz", level: "fluent" },
      { name: "Rus", level: "fluent" },
    ],
    responseTimeHours: 5,
    available: false,
    rating: 4.6,
    completedContracts: 6,
    badge: "ishonchli",
    memberSince: "2026-03-18T08:30:00.000Z",
  },
  "u-8": {
    userId: "u-8",
    headline: "DevOps & Cloud Server Arxitektori",
    bio: "CI/CD pipeline, Kubernetes, Docker va Linux serverlar xavfsizligi.",
    location: "Toshkent",
    skills: ["DevOps", "Docker", "Kubernetes", "Linux", "CI/CD", "AWS"],
    categories: ["dasturlash"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Ingliz", level: "fluent" }],
    responseTimeHours: 1,
    available: true,
    rating: 5.0,
    completedContracts: 5,
    badge: "ishonchli",
    memberSince: "2026-04-01T10:00:00.000Z",
  },
};

export const seedServices: Service[] = [
  {
    id: "svc-1",
    sellerId: "u-1",
    title: "Next.js va Tailwind CSS asosida zamonaviy veb-sayt",
    description: "Tezkor, SEO optimallashgan va moslashuvchan (responsive) veb-sayt yaratib beraman. Clean architecture va to'liq kod topshiriladi.",
    price: 3500000,
    currency: "UZS",
    deliveryDays: 5,
    category: "dasturlash",
    images: svgGallery("svc-1", "dasturlash", 2),
    fields: {
      type: "Landing page",
      tech: "Next.js 15, Tailwind, TS",
    },
    status: "active",
    createdAt: "2026-02-01T10:00:00.000Z",
    revisionsIncluded: 2,
    included: ["To'liq manba kodi (Git repozitoriy)", "Responsive dizayn (mobil/planshet/desktop)", "Asosiy SEO sozlamalari"],
    requirements: ["Loyihaning texnik topshirig'i yoki maqsadi", "Domen va hosting ma'lumotlari (mavjud bo'lsa)"],
    extras: [
      { label: "Tezkor topshirish (5 kun o'rniga 3 kun)", price: 700000 },
      { label: "Ko'p tilli qo'llab-quvvatlash (UZ/RU/EN)", price: 1200000 },
    ],
  },
  {
    id: "svc-2",
    sellerId: "u-2",
    title: "Mukammal Logotip va Brandbook dizayni",
    description: "Kompaniyangiz uchun esda qolarli logotip, ranglar palitrasi, shriftlar va to'liq brendbuk ishlab chiqaman.",
    price: 2000000,
    currency: "UZS",
    deliveryDays: 4,
    category: "dizayn",
    images: svgGallery("svc-2", "dizayn", 2),
    fields: {
      variants: "3 ta konseptsiya",
      format: "Vector (AI, SVG, PNG)",
    },
    status: "active",
    createdAt: "2026-02-05T12:00:00.000Z",
    revisionsIncluded: 3,
    included: ["3 ta noyob konseptsiya", "Vektor fayllar (AI, SVG, PNG)", "Ranglar palitrasi va shrift yo'riqnomasi"],
    requirements: ["Kompaniya nomi va faoliyat sohasi", "Yoqqan uslub yoki raqobatchi misollar"],
    extras: [{ label: "Vizitka va blank dizayni", price: 400000 }],
  },
  {
    id: "svc-3",
    sellerId: "u-3",
    title: "Biznes uchun Telegram CRM va To'lovli Bot",
    description: "Click va Payme ulangan, administrator panelli va avtomatlashtirilgan xabarnomali mukammal Telegram bot.",
    price: 1800000,
    currency: "UZS",
    deliveryDays: 3,
    category: "dasturlash",
    images: svgGallery("svc-3", "dasturlash", 1),
    fields: {
      lang: "Python / Aiogram",
      database: "PostgreSQL",
    },
    status: "active",
    createdAt: "2026-02-10T14:30:00.000Z",
    revisionsIncluded: 2,
    included: ["Click va Payme integratsiyasi", "Administrator boshqaruv paneli", "1 oylik texnik yordam"],
    requirements: ["Click/Payme merchant hisob ma'lumotlari", "Bot funksiyalari ro'yxati (texnik topshiriq)"],
  },
  {
    id: "svc-4",
    sellerId: "u-4",
    title: "1 oylik kompleks Instagram SMM boshqaruvi",
    description: "Profil tahlili, 15 ta post, 30 ta story, 8 ta reels va target reklama kampaniyasini sozlash.",
    price: 3000000,
    currency: "UZS",
    deliveryDays: 30,
    category: "marketing",
    images: svgGallery("svc-4", "marketing", 1),
    fields: {
      coverage: "1 oylik to'liq yuritish",
    },
    status: "active",
    createdAt: "2026-02-15T09:00:00.000Z",
    revisionsIncluded: 1,
    included: ["15 ta post + 30 ta story + 8 ta reels", "Target reklama kampaniyasi sozlash", "Oylik hisobot"],
    requirements: ["Instagram profiliga administrator huquqi", "Brend ranglari va logotip fayllari"],
  },
  {
    id: "svc-5",
    sellerId: "u-5",
    title: "Cross-platform Flutter mobil ilova yaratish",
    description: "iOS va Android tizimlari uchun chiroyli UI va tezkor backend integratsiyali mobil ilova.",
    price: 7500000,
    currency: "UZS",
    deliveryDays: 14,
    category: "dasturlash",
    images: svgGallery("svc-5", "dasturlash", 1),
    fields: {
      framework: "Flutter 3",
      platforms: "iOS & Android",
    },
    status: "active",
    createdAt: "2026-02-20T11:20:00.000Z",
    revisionsIncluded: 2,
    included: ["iOS va Android uchun bitta kod bazasi", "Backend API integratsiyasi", "App Store/Play Market'ga joylash bo'yicha yordam"],
    requirements: ["Dizayn maketi (Figma) yoki g'oya tavsifi", "Backend API hujjatlari (mavjud bo'lsa)"],
  },
  {
    id: "svc-6",
    sellerId: "u-6",
    title: "Sayt va Landing Page uchun SEO Kopirayting",
    description: "Google va Yandex qidiruv tizimlarida yuqori o'rinlarga chiqish uchun professional SEO matnlar.",
    price: 900000,
    currency: "UZS",
    deliveryDays: 2,
    category: "kontent",
    images: svgGallery("svc-6", "kontent", 1),
    fields: {
      words: "2000 so'z",
      seo: "Kalit so'zlar bilan",
    },
    status: "active",
    createdAt: "2026-02-25T16:00:00.000Z",
    revisionsIncluded: 1,
    included: ["2000 so'zli SEO-optimallashgan matn", "Kalit so'zlar tahlili", "Meta sarlavha va tavsif"],
    requirements: ["Sayt/mahsulot haqida qisqa ma'lumot", "Maqsadli kalit so'zlar (mavjud bo'lsa)"],
  },
];

export const seedJobs: Job[] = [
  {
    id: "job-1",
    buyerId: "u-b1",
    buyerName: "TechCorp Tashkent MChJ",
    buyerRating: 4.9,
    title: "E-Commerce veb-saytini qayta dizayn qilish va Next.js ga o'tkazish",
    description: "Mavjud online do'konimizni zamonaviy UI/UX asosida yangilash va tezkor Next.js frontendiga o'tkazish talab etiladi.",
    category: "dasturlash",
    budgetMin: 6000000,
    budgetMax: 8000000,
    currency: "UZS",
    skillsRequired: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    screeningQuestions: ["Avval e-commerce loyihasi bajarganmisiz?"],
    proposalsCount: 4,
    postedAt: "2026-03-01T10:00:00.000Z",
    status: "ochiq",
  },
  {
    id: "job-2",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios",
    buyerRating: 5.0,
    title: "Logistika kompaniyasi uchun brendbuk va korporativ uslub",
    description: "Kompaniyamiz avtoparki, hujjatlar blankalari va ofis uchun to'liq vizual uslub kerak.",
    category: "dizayn",
    budgetMin: 3500000,
    budgetMax: 4500000,
    currency: "UZS",
    skillsRequired: ["Brandbook", "Logotip", "Figma", "Illustrator"],
    screeningQuestions: [],
    proposalsCount: 2,
    postedAt: "2026-03-05T12:00:00.000Z",
    status: "ochiq",
  },
  {
    id: "job-3",
    buyerId: "u-b3",
    buyerName: "Zamona Logistics",
    buyerRating: 4.8,
    title: "Omborxona qoldiqlarini boshqaruvchi Telegram Bot",
    description: "Omborga tovar kelishi va ketishini hisobga oluvchi, Excel formatida hisobot beruvchi bot kerak.",
    category: "dasturlash",
    budgetMin: 2000000,
    budgetMax: 2500000,
    currency: "UZS",
    skillsRequired: ["Python", "Telegram Bot", "PostgreSQL"],
    screeningQuestions: [],
    proposalsCount: 3,
    postedAt: "2026-03-10T15:00:00.000Z",
    status: "yopilgan",
  },
  /* Ochiq e'lonlar — demo mutaxassis (u-1, "dasturlash") hali taklif
     yubormagan. Ularsiz boshqaruvdagi "Sizga mos e'lonlar" bloki va ish
     e'lonlari sahifasi bo'sh chiqardi: job-1 ga u allaqachon taklif
     yuborgan, job-3 esa yopilgan. */
  {
    id: "job-4",
    buyerId: "u-b4",
    buyerName: "Farrux Zokirov",
    buyerRating: 4.7,
    title: "SaaS mahsulot uchun analitika paneli (dashboard)",
    description: "Mavjud API'ga ulanadigan, grafik va filtrlarga ega admin dashboard kerak. Dizayn maketi tayyor, faqat frontend dasturlash.",
    category: "dasturlash",
    budgetMin: 4000000,
    budgetMax: 5500000,
    currency: "UZS",
    skillsRequired: ["React", "TypeScript", "Tailwind CSS"],
    screeningQuestions: ["Grafik kutubxonalaridan qaysilari bilan ishlagansiz?"],
    proposalsCount: 2,
    postedAt: "2026-04-13T09:00:00.000Z",
    status: "ochiq",
  },
  {
    id: "job-5",
    buyerId: "u-b5",
    buyerName: "Apex Retail Group",
    buyerRating: 4.6,
    title: "Ichki hisobot tizimi uchun Next.js frontend",
    description: "PostgreSQL bazadagi savdo ma'lumotlarini ko'rsatuvchi ichki panel. Autentifikatsiya va rollar tizimi ham kerak.",
    category: "dasturlash",
    budgetMin: 6000000,
    budgetMax: 9000000,
    currency: "UZS",
    skillsRequired: ["Next.js", "Node.js", "PostgreSQL"],
    screeningQuestions: [],
    proposalsCount: 1,
    postedAt: "2026-04-14T11:30:00.000Z",
    status: "ochiq",
  },
  {
    id: "job-6",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios (Mijoz)",
    buyerRating: 5.0,
    title: "Mobil ilova uchun ikonkalar to'plami va illustratsiyalar",
    description: "30 ta ikonka (outline + filled) va 4 ta onboarding illustratsiyasi. Uslub qo'llanmasi beriladi.",
    category: "dizayn",
    budgetMin: 1500000,
    budgetMax: 2200000,
    currency: "UZS",
    skillsRequired: ["Figma", "Illustrator", "Icon Design"],
    screeningQuestions: [],
    proposalsCount: 0,
    postedAt: "2026-04-14T16:00:00.000Z",
    status: "ochiq",
  },
];

export const seedProposals: Proposal[] = [
  {
    id: "prop-1",
    jobId: "job-1",
    sellerId: "u-1",
    bidAmount: 7500000,
    coverLetter: "Assalomu alaykum. E-commerce bo'yicha katta tajribam bor. Next.js va Tailwind'da tezkor do'kon yaratib bera olaman.",
    screeningAnswers: [{ question: "Avval e-commerce loyihasi bajarganmisiz?", answer: "Ha, 3 ta yirik do'kon yaratganman." }],
    attachedImages: [],
    status: "yollandi",
    createdAt: "2026-03-02T11:00:00.000Z",
  },
  {
    id: "prop-2",
    jobId: "job-2",
    sellerId: "u-2",
    bidAmount: 4000000,
    coverLetter: "Assalomu alaykum. Logistika va B2B brending loyihalarida tajribam bor. 3 xil konseptsiya taqdim etaman.",
    screeningAnswers: [],
    attachedImages: [],
    status: "korib_chiqilmoqda",
    createdAt: "2026-03-06T14:00:00.000Z",
  },
];

export const seedContracts: Contract[] = [
  {
    id: "cnt-1",
    title: "E-Commerce veb-saytini qayta dizayn qilish va Next.js ga o'tkazish",
    buyerId: "u-b1",
    buyerName: "TechCorp Tashkent MChJ",
    sellerId: "u-1",
    sellerName: "Rustam Qosimov",
    sourceType: "taklif",
    jobId: "job-1",
    totalAmount: 7500000,
    status: "faol",
    createdAt: "2026-03-03T10:00:00.000Z",
  },
  {
    id: "cnt-2",
    title: "Mukammal Logotip va Brandbook dizayni",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios",
    sellerId: "u-2",
    sellerName: "Nigora Karimova",
    sourceType: "xizmat",
    serviceId: "svc-2",
    totalAmount: 2000000,
    status: "yakunlangan",
    createdAt: "2026-02-10T11:00:00.000Z",
  },
  {
    id: "cnt-3",
    title: "Biznes uchun Telegram CRM va To'lovli Bot",
    buyerId: "u-b3",
    buyerName: "Zamona Logistics",
    sellerId: "u-3",
    sellerName: "Jasur Bekchanov",
    sourceType: "xizmat",
    serviceId: "svc-3",
    totalAmount: 1800000,
    status: "nizo",
    createdAt: "2026-02-18T14:00:00.000Z",
  },
  {
    id: "cnt-4",
    title: "Cross-platform Flutter mobil ilova yaratish",
    buyerId: "u-b5",
    buyerName: "Apex Retail Group",
    sellerId: "u-5",
    sellerName: "Umid Aliyev",
    sourceType: "xizmat",
    serviceId: "svc-5",
    totalAmount: 7500000,
    status: "nizo",
    createdAt: "2026-03-12T16:00:00.000Z",
  },
  /* MAHSULOTNING ASOSIY G'OYASINI demo qilish uchun: `imzolangan` — taraflar
     kelishgan, lekin xaridor hali escrow'ga to'lamagan, ish BOSHLANMAGAN.
     Barcha bosqich `kutilmoqda`. Xaridor (u-b2) `fundContract` bilan butun
     summani bitta to'lovda tashlaydi → shartnoma `faol` bo'ladi.
     Ilgari seed'da bunday shartnoma yo'q edi va escrow to'lovini ko'rsatish
     uchun avval qo'lda taklif yuborib, uni qabul qilish kerak bo'lardi. */
  {
    id: "cnt-5",
    title: "Ichki CRM uchun hisobot moduli",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios (Mijoz)",
    sellerId: "u-1",
    sellerName: "Rustam Qosimov",
    sourceType: "taklifnoma",
    totalAmount: 5000000,
    status: "imzolangan",
    createdAt: "2026-03-16T12:30:00.000Z",
  },
];

export const seedMilestones: Milestone[] = [
  {
    id: "ms-1-1",
    contractId: "cnt-1",
    title: "1-Bosqich: Figma Dizayn va Prototip",
    description: "To'liq UI/UX dizayn va interaktiv prototip topshirish",
    amount: 3500000,
    status: "qabul_qilindi",
    dueDate: "2026-03-05T00:00:00.000Z",
    submittedAt: "2026-03-05T16:00:00.000Z",
    approvedAt: "2026-03-05T17:00:00.000Z",
  },
  {
    id: "ms-1-2",
    contractId: "cnt-1",
    title: "2-Bosqich: Next.js Frontend Dasturlash",
    description: "Responsive veb-ilova va API integratsiyasi",
    amount: 4000000,
    status: "mablaglangan",
    dueDate: "2026-04-28T00:00:00.000Z",
  },
  {
    id: "ms-2-1",
    contractId: "cnt-2",
    title: "Logotip va Brandbook yakuniy topshirish",
    description: "3 ta konseptsiya va vektor fayllar",
    amount: 2000000,
    status: "qabul_qilindi",
    dueDate: "2026-02-15T00:00:00.000Z",
    submittedAt: "2026-02-14T14:00:00.000Z",
    approvedAt: "2026-02-15T10:00:00.000Z",
  },
  {
    id: "ms-3-1",
    contractId: "cnt-3",
    title: "Telegram Bot to'liq funksional",
    description: "Bot dasturlash va to'lovlar integratsiyasi",
    amount: 1800000,
    status: "topshirildi",
    dueDate: "2026-02-28T00:00:00.000Z",
    submittedAt: "2026-02-28T18:00:00.000Z",
  },
  {
    id: "ms-4-1",
    contractId: "cnt-4",
    title: "Mobil ilova MVP topshirish",
    description: "iOS va Android uchun dastlabki versiya",
    amount: 7500000,
    status: "topshirildi",
    dueDate: "2026-04-10T00:00:00.000Z",
    submittedAt: "2026-04-10T15:00:00.000Z",
  },
  /* cnt-5 bosqichlari — hammasi `kutilmoqda`: to'lov kutilmoqda, ish
     boshlanmagan. `fundContract` ikkalasini birdan `mablaglangan` qiladi. */
  {
    id: "ms-5-1",
    contractId: "cnt-5",
    title: "1-Bosqich: Ma'lumot qatlami va API",
    description: "Hisobot uchun ma'lumotlar bazasi so'rovlari va API endpointlari",
    amount: 2000000,
    status: "kutilmoqda",
    dueDate: "2026-05-05T00:00:00.000Z",
  },
  {
    id: "ms-5-2",
    contractId: "cnt-5",
    title: "2-Bosqich: Hisobot ekranlari va eksport",
    description: "Grafiklar, filtrlar va Excel eksporti",
    amount: 3000000,
    status: "kutilmoqda",
    dueDate: "2026-05-20T00:00:00.000Z",
  },
];

export const seedMessages: Message[] = [
  {
    id: "msg-1",
    contractId: "cnt-1",
    senderId: "u-b1",
    text: "Salom Rustam! Figma maketlarini kutib qolamiz.",
    createdAt: "2026-03-03T10:30:00.000Z",
  },
  {
    id: "msg-2",
    contractId: "cnt-1",
    senderId: "u-1",
    text: "Salom! Figma maketlari tayyor bo'ldi, havola: figma.com/file/xyz",
    createdAt: "2026-03-05T16:00:00.000Z",
  },
];

/* To'g'ridan-to'g'ri takliflar (A yo'l).
   Ataylab DEMO hisoblar orasida: xaridor u-b2 (ArtSoft) → mutaxassis u-1
   (Rustam). Shunda bitta brauzerda hisob almashtirib, taklifni ikkala
   tomondan ham ko'rish mumkin. Ilgari bu massiv bo'sh edi — natijada A yo'l
   oqimini (taklif → chat → qabul) demo qilish uchun avval qo'lda taklif
   yuborish kerak bo'lardi. */
export const seedOffers: Offer[] = [
  {
    id: "off-1",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios (Mijoz)",
    sellerId: "u-1",
    sellerName: "Rustam Qosimov",
    serviceId: "svc-1",
    title: "Korporativ sayt: 5 sahifa + admin panel",
    message:
      "Assalomu alaykum Rustam. Kompaniyamiz uchun 5 sahifali korporativ sayt va oddiy admin panel kerak. Xizmatingizni ko'rdim, muddat va narx bo'yicha kelisha olamizmi?",
    budget: 6500000,
    status: "yuborilgan",
    createdAt: "2026-03-14T09:20:00.000Z",
  },
  {
    id: "off-2",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios (Mijoz)",
    sellerId: "u-1",
    sellerName: "Rustam Qosimov",
    title: "Ichki CRM uchun hisobot moduli",
    message:
      "CRM tizimimizga sotuv hisobotlari moduli kerak. Bosqichma-bosqich ishlasak bo'ladi.",
    budget: 5000000,
    status: "qabul_qilindi",
    contractId: "cnt-5",
    createdAt: "2026-03-16T11:00:00.000Z",
  },
  {
    id: "off-3",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios (Mijoz)",
    sellerId: "u-4",
    sellerName: "Zarina Saidova",
    title: "Instagram uchun 10 ta reels montaji",
    message: "Oyiga 10 ta qisqa reels montaj qilib bera olasizmi?",
    budget: 1200000,
    status: "rad_etildi",
    createdAt: "2026-03-11T15:40:00.000Z",
  },
];

/* Taklif chatidagi xabarlar — contractId maydoni taklif id'siga bog'lanadi. */
export const seedOfferMessages: Message[] = [
  {
    id: "omsg-1",
    contractId: "off-1",
    senderId: "u-b2",
    text: "Assalomu alaykum Rustam. Kompaniyamiz uchun 5 sahifali korporativ sayt va oddiy admin panel kerak. Xizmatingizni ko'rdim, muddat va narx bo'yicha kelisha olamizmi?",
    createdAt: "2026-03-14T09:20:00.000Z",
  },
  {
    id: "omsg-2",
    contractId: "off-2",
    senderId: "u-b2",
    text: "CRM tizimimizga sotuv hisobotlari moduli kerak. Bosqichma-bosqich ishlasak bo'ladi.",
    createdAt: "2026-03-16T11:00:00.000Z",
  },
  {
    id: "omsg-3",
    contractId: "off-2",
    senderId: "u-1",
    text: "Salom! Vazifa tushunarli. Ikki bosqichga bo'lamiz: ma'lumot qatlami va hisobot ekranlari. Shartnomani ochdim.",
    createdAt: "2026-03-16T12:30:00.000Z",
  },
];

export const seedReviews: Review[] = [
  {
    id: "rev-1",
    contractId: "cnt-2",
    buyerName: "ArtSoft Studios",
    sellerId: "u-2",
    rating: 5,
    comment: "Ajoyib ish! Nigora juda kreativ va belgilangan muddatdan oldin logotipni taqdim etdi. Tavsiya qilaman!",
    createdAt: "2026-02-15T10:00:00.000Z",
  },
  /* Demo mutaxassis (u-1) profilida ham sharh bo'lsin — ochiq profil va
     bozor kartasi reyting bilan birga sharhlarni ham ko'rsatadi. */
  {
    id: "rev-2",
    contractId: "cnt-1",
    buyerName: "TechCorp Tashkent MChJ",
    sellerId: "u-1",
    rating: 5,
    comment:
      "Figma maketlari bir kunda tayyor bo'ldi, kod sifati yuqori. Bosqichli to'lov ikkala tomon uchun ham qulay chiqdi.",
    createdAt: "2026-03-06T09:00:00.000Z",
  },
  {
    id: "rev-3",
    contractId: "cnt-2",
    buyerName: "Farrux Zokirov",
    sellerId: "u-1",
    rating: 4,
    comment:
      "Ish sifatli bajarildi. Bir bosqichda kichik kechikish bo'ldi, lekin oldindan ogohlantirdi.",
    createdAt: "2026-02-20T13:30:00.000Z",
  },
];

/* Bildirishnomalar — Header qo'ng'irog'i `userId` bo'yicha filtrlaydi.
   Ilgari bo'sh edi: qo'ng'iroq har doim "Hozircha bildirishnoma yo'q" derdi
   va uni demo qilib bo'lmasdi. Har ikkala demo hisobda ham o'qilmagan
   bildirishnoma bo'lishi uchun ataylab ikkala tomonga yozilgan. */
export const seedNotifications: AppNotification[] = [
  {
    id: "ntf-1",
    userId: "u-1",
    kind: "taklif",
    messageKey: "ntf.newOffer",
    params: { title: "Korporativ sayt: 5 sahifa + admin panel" },
    href: "/mutaxassis/takliflarim/kelgan/off-1",
    read: false,
    createdAt: "2026-03-14T09:20:00.000Z",
  },
  {
    id: "ntf-2",
    userId: "u-1",
    kind: "xabar",
    messageKey: "ntf.newMessage",
    params: { title: "Ichki CRM uchun hisobot moduli" },
    href: "/mutaxassis/shartnomalar/cnt-5",
    read: false,
    createdAt: "2026-03-16T11:05:00.000Z",
  },
  {
    id: "ntf-3",
    userId: "u-1",
    kind: "bosqich",
    messageKey: "ntf.milestoneAccepted",
    params: { title: "1-Bosqich: Figma Dizayn va Prototip" },
    href: "/mutaxassis/shartnomalar/cnt-1",
    read: true,
    createdAt: "2026-03-05T17:00:00.000Z",
  },
  {
    id: "ntf-4",
    userId: "u-b2",
    kind: "taklif",
    messageKey: "ntf.offerAccepted",
    params: { title: "Ichki CRM uchun hisobot moduli" },
    href: "/xaridor/shartnomalar/cnt-5",
    read: false,
    createdAt: "2026-03-16T12:30:00.000Z",
  },
  {
    id: "ntf-5",
    userId: "u-b2",
    kind: "taklif",
    messageKey: "ntf.offerDeclined",
    params: { title: "Instagram uchun 10 ta reels montaji" },
    href: "/xaridor/takliflarim/off-3",
    read: true,
    createdAt: "2026-03-12T08:15:00.000Z",
  },
];

/* KYC yozuvlari — ochiq profildagi "Shaxsi tasdiqlangan" belgisi shu
   ro'yxatdan hisoblanadi (`verifiedIdentitySet`). Ilgari bu ma'lumot
   admin panelining mock faylida turardi va asosiy ilova unga bog'liq edi;
   admin alohida branch'ga chiqarilgach, u shu yerga ko'chirildi. */
export const seedVerifications: VerificationRecord[] = [
  {
    userId: "u-1",
    status: "tasdiqlangan",
    country: "UZ",
    documentType: "passport",
    legalName: "Rustam Qosimov",
    birthDate: "1994-05-12",
    documents: [
      svgImg("kyc-u-1")
    ],
    submittedAt: "2026-01-12T10:00:00.000Z",
  },
  {
    userId: "u-2",
    status: "tasdiqlangan",
    country: "UZ",
    documentType: "id_card",
    legalName: "Nigora Karimova",
    birthDate: "1997-08-23",
    documents: [
      svgImg("kyc-u-2")
    ],
    submittedAt: "2026-01-16T12:00:00.000Z",
  },
  {
    userId: "u-3",
    status: "tasdiqlangan",
    country: "UZ",
    documentType: "passport",
    legalName: "Jasur Bekchanov",
    birthDate: "1996-11-04",
    documents: [
      svgImg("kyc-u-3")
    ],
    submittedAt: "2026-02-02T09:00:00.000Z",
  },
  {
    userId: "u-4",
    status: "korib_chiqilmoqda",
    country: "UZ",
    documentType: "id_card",
    legalName: "Zarina Saidova",
    birthDate: "1999-03-15",
    documents: [
      svgImg("kyc-u-4")
    ],
    submittedAt: "2026-04-18T10:30:00.000Z",
  },
  {
    userId: "u-5",
    status: "korib_chiqilmoqda",
    country: "UZ",
    documentType: "passport",
    legalName: "Umid Aliyev",
    birthDate: "1995-09-30",
    documents: [
      svgImg("kyc-u-5")
    ],
    submittedAt: "2026-04-19T14:15:00.000Z",
  },
  {
    userId: "u-6",
    status: "korib_chiqilmoqda",
    country: "UZ",
    documentType: "id_card",
    legalName: "Shahzod Mirzayev",
    birthDate: "1998-01-18",
    documents: [
      svgImg("kyc-u-6")
    ],
    submittedAt: "2026-04-20T08:45:00.000Z",
  },
  {
    userId: "u-7",
    status: "rad_etilgan",
    country: "UZ",
    documentType: "passport",
    legalName: "Aziza Toshmatova",
    birthDate: "2000-07-09",
    documents: [
      svgImg("kyc-u-7")
    ],
    submittedAt: "2026-03-20T16:00:00.000Z",
    rejectionReason: "Hujjat surati xira va chetlari kesilgan. Iltimos, sifatliroq formatda qayta yuklang.",
  },
  {
    userId: "u-sus1",
    status: "rad_etilgan",
    country: "UZ",
    documentType: "passport",
    legalName: "Botir Qobilov",
    birthDate: "1993-12-05",
    documents: [
      svgImg("kyc-u-sus1")
    ],
    submittedAt: "2026-04-10T12:30:00.000Z",
    rejectionReason: "Taqdim etilgan passport boshqa foydalanuvchi hisobiga tegishli.",
  },
];
