import type {
  AppNotification,
  Contract,
  Job,
  Message,
  Milestone,
  Offer,
  Proposal,
  Review,
  SellerProfile,
  Service,
  User,
} from "@/lib/types";

export const BUYER_ID = "u-b2";
export const SELLER_ID = "u-1";
export const DEMO_PASSWORD = "demo123";

export const seedUsers: User[] = [
  {
    id: "u-1",
    fullName: "Rustam Qosimov",
    phone: "+998901234567",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-01-10T10:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-2",
    fullName: "Nigora Karimova",
    phone: "+998912345678",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-01-15T11:30:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-3",
    fullName: "Jasur Bekchanov",
    phone: "+998933456789",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-02-01T09:15:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-4",
    fullName: "Zarina Saidova",
    phone: "+998944567890",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-02-12T14:20:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-5",
    fullName: "Umid Aliyev",
    phone: "+998975678901",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-03-01T16:45:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-6",
    fullName: "Shahzod Mirzayev",
    phone: "+998996789012",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-03-10T12:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-7",
    fullName: "Aziza Toshmatova",
    phone: "+998907890123",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-03-18T08:30:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-8",
    fullName: "Bobur Ahmedov",
    phone: "+998918901234",
    role: "mutaxassis",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-04-01T10:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b1",
    fullName: "TechCorp Tashkent MChJ",
    phone: "+998909876543",
    role: "xaridor",
    avatarUrl: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-01-05T09:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b2",
    fullName: "ArtSoft Studios (Mijoz)",
    phone: "+998918765432",
    role: "xaridor",
    avatarUrl: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-01-12T14:10:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b3",
    fullName: "Zamona Logistics",
    phone: "+998937654321",
    role: "xaridor",
    avatarUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-02-20T11:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b4",
    fullName: "Farrux Zokirov",
    phone: "+998946543210",
    role: "xaridor",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-03-05T15:30:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-b5",
    fullName: "Apex Retail Group",
    phone: "+998975432109",
    role: "xaridor",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    createdAt: "2026-03-25T10:45:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: true,
  },
  {
    id: "u-sus1",
    fullName: "Botir Qobilov",
    phone: "+998901112233",
    role: "mutaxassis",
    createdAt: "2026-04-10T12:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
  {
    id: "u-block1",
    fullName: "CopyMaster_UZ",
    phone: "+998993334455",
    role: "mutaxassis",
    createdAt: "2026-04-15T09:00:00.000Z",
    roleChosen: true,
    profileDone: true,
    verified: false,
  },
];

export const seedProfiles: Record<string, SellerProfile> = {
  "u-1": {
    userId: "u-1",
    headline: "Senior Fullstack & Next.js Dasturchi",
    bio: "7 yillik tajribaga ega dasturchi. Next.js, React, Node.js, PostgreSQL va murakkab fintech tizimlarni yaratish bo'yicha mutaxassis.",
    location: "Toshkent",
    skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
    categories: ["dasturlash"],
    portfolio: [
      {
        id: "port-1",
        title: "Fintech E-Wallet Web Platformasi",
        description: "To'lovlar va transaksiyalar uchun yuqori yuklamali veb ilova.",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
        category: "dasturlash",
      },
      {
        id: "port-2",
        title: "B2B E-Commerce Marketplace",
        description: "Ulgurji savdo uchun avtomatlashtirilgan katalog va ombor boshqaruvi.",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
        category: "dasturlash",
      },
    ],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Rus", level: "fluent" },
      { name: "Ingliz", level: "intermediate" },
    ],
    responseTimeHours: 1,
    available: true,
    rating: 4.9,
    completedContracts: 26,
    badge: "top_mutaxassis",
    memberSince: "2026-01-10T10:00:00.000Z",
  },
  "u-2": {
    userId: "u-2",
    headline: "Senior UI/UX Dizayner & Brending Mutaxassisi",
    bio: "Figma, Design System va foydalanuvchi tajribasini (UX) chuqur tushunuvchi dizayner. 50+ dan ortiq muvaffaqiyatli loyihalar.",
    location: "Samarqand",
    skills: ["Figma", "UI/UX", "Mobile Design", "Brand Identity", "Design System"],
    categories: ["dizayn"],
    portfolio: [
      {
        id: "port-3",
        title: "Bank Mobil Ilovasi UI/UX",
        description: "Minimalist va qulay foydalanuvchi interfeysi.",
        image: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800&auto=format&fit=crop&q=80",
        category: "dizayn",
      },
    ],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Rus", level: "fluent" },
      { name: "Ingliz", level: "fluent" },
    ],
    responseTimeHours: 2,
    available: true,
    rating: 5.0,
    completedContracts: 28,
    badge: "top_mutaxassis",
    memberSince: "2026-01-15T11:30:00.000Z",
  },
  "u-3": {
    userId: "u-3",
    headline: "Telegram Bot & Python Backend Mutaxassisi",
    bio: "Aiogram, FastAPI, PostgreSQL va to'lov tizimlari (Click, Payme) integratsiyalari bo'yicha 4 yillik tajriba.",
    location: "Xorazm",
    skills: ["Python", "Telegram Bot", "FastAPI", "PostgreSQL", "Docker", "Click / Payme"],
    categories: ["dasturlash"],
    portfolio: [
      {
        id: "port-4",
        title: "Yetkazib berish xizmati uchun Telegram Bot",
        description: "Geolokatsiya va onlayn to'lovli avtomatlashtirilgan buyurtma boti.",
        image: "https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80",
        category: "dasturlash",
      },
    ],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Rus", level: "intermediate" },
    ],
    responseTimeHours: 3,
    available: true,
    rating: 4.8,
    completedContracts: 16,
    badge: "ishonchli",
    memberSince: "2026-02-01T09:15:00.000Z",
  },
  "u-4": {
    userId: "u-4",
    headline: "SMM Strateg & Instagram Content Creator",
    bio: "Brendlarni ijtimoiy tarmoqlarda o'stirish, reklama kampaniyalari va kreativ vizual kontent yaratish bo'yicha ekspert.",
    location: "Toshkent",
    skills: ["SMM", "Instagram", "Targeting", "Reels", "Content Strategy"],
    categories: ["marketing"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Rus", level: "fluent" }],
    responseTimeHours: 1,
    available: true,
    rating: 4.7,
    completedContracts: 11,
    badge: "ishonchli",
    memberSince: "2026-02-12T14:20:00.000Z",
  },
  "u-5": {
    userId: "u-5",
    headline: "Flutter & React Native Mobil Dasturchi",
    bio: "iOS va Android uchun bir vaqtda ishlaydigan zamonaviy, tezkor va xavfsiz mobil ilovalar yaratish.",
    location: "Buxoro",
    skills: ["Flutter", "Dart", "React Native", "iOS", "Android", "REST API"],
    categories: ["dasturlash"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Ingliz", level: "fluent" }],
    responseTimeHours: 4,
    available: true,
    rating: 4.9,
    completedContracts: 10,
    badge: "ishonchli",
    memberSince: "2026-03-01T16:45:00.000Z",
  },
  "u-6": {
    userId: "u-6",
    headline: "Professional SEO & Texnik Kopirayter",
    bio: "Saytlar va bizneslar uchun yuqori konversiyali matnlar, maqolalar va texnik hujjatlar yozish.",
    location: "Namangan",
    skills: ["Kopirayting", "SEO", "Texnik matnlar", "Blog"],
    categories: ["kontent"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Rus", level: "fluent" }],
    responseTimeHours: 2,
    available: true,
    rating: 4.8,
    completedContracts: 8,
    badge: "ishonchli",
    memberSince: "2026-03-10T12:00:00.000Z",
  },
  "u-7": {
    userId: "u-7",
    headline: "Ingliz va Rus tillari Tarjimoni",
    bio: "Texnik, yuridik va ilmiy matnlarni yuqori aniqlikda tarjima qilish.",
    location: "Farg'ona",
    skills: ["Tarjima", "Ingliz tili", "Rus tili", "Tahrirlash"],
    categories: ["tarjima"],
    portfolio: [],
    languages: [
      { name: "O'zbek", level: "native" },
      { name: "Ingliz", level: "fluent" },
      { name: "Rus", level: "fluent" },
    ],
    responseTimeHours: 5,
    available: false,
    rating: 4.6,
    completedContracts: 6,
    badge: "ishonchli",
    memberSince: "2026-03-18T08:30:00.000Z",
  },
  "u-8": {
    userId: "u-8",
    headline: "DevOps & Cloud Server Arxitektori",
    bio: "CI/CD pipeline, Kubernetes, Docker va Linux serverlar xavfsizligi.",
    location: "Toshkent",
    skills: ["DevOps", "Docker", "Kubernetes", "Linux", "CI/CD", "AWS"],
    categories: ["dasturlash"],
    portfolio: [],
    languages: [{ name: "O'zbek", level: "native" }, { name: "Ingliz", level: "fluent" }],
    responseTimeHours: 1,
    available: true,
    rating: 5.0,
    completedContracts: 5,
    badge: "ishonchli",
    memberSince: "2026-04-01T10:00:00.000Z",
  },
};

export const seedServices: Service[] = [
  {
    id: "svc-1",
    sellerId: "u-1",
    title: "Next.js va Tailwind CSS asosida zamonaviy veb-sayt",
    description: "Tezkor, SEO optimallashgan va moslashuvchan (responsive) veb-sayt yaratib beraman. Clean architecture va to'liq kod topshiriladi.",
    price: 3500000,
    currency: "UZS",
    deliveryDays: 5,
    category: "dasturlash",
    images: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
    ],
    fields: {
      type: "Landing page",
      tech: "Next.js 15, Tailwind, TS",
    },
    status: "active",
    createdAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "svc-2",
    sellerId: "u-2",
    title: "Mukammal Logotip va Brandbook dizayni",
    description: "Kompaniyangiz uchun esda qolarli logotip, ranglar palitrasi, shriftlar va to'liq brendbuk ishlab chiqaman.",
    price: 2000000,
    currency: "UZS",
    deliveryDays: 4,
    category: "dizayn",
    images: [
      "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800&auto=format&fit=crop&q=80",
    ],
    fields: {
      variants: "3 ta konseptsiya",
      format: "Vector (AI, SVG, PNG)",
    },
    status: "active",
    createdAt: "2026-02-05T12:00:00.000Z",
  },
  {
    id: "svc-3",
    sellerId: "u-3",
    title: "Biznes uchun Telegram CRM va To'lovli Bot",
    description: "Click va Payme ulangan, administrator panelli va avtomatlashtirilgan xabarnomali mukammal Telegram bot.",
    price: 1800000,
    currency: "UZS",
    deliveryDays: 3,
    category: "dasturlash",
    images: [
      "https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80",
    ],
    fields: {
      lang: "Python / Aiogram",
      database: "PostgreSQL",
    },
    status: "active",
    createdAt: "2026-02-10T14:30:00.000Z",
  },
  {
    id: "svc-4",
    sellerId: "u-4",
    title: "1 oylik kompleks Instagram SMM boshqaruvi",
    description: "Profil tahlili, 15 ta post, 30 ta story, 8 ta reels va target reklama kampaniyasini sozlash.",
    price: 3000000,
    currency: "UZS",
    deliveryDays: 30,
    category: "marketing",
    images: [
      "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=80",
    ],
    fields: {
      coverage: "1 oylik to'liq yuritish",
    },
    status: "active",
    createdAt: "2026-02-15T09:00:00.000Z",
  },
  {
    id: "svc-5",
    sellerId: "u-5",
    title: "Cross-platform Flutter mobil ilova yaratish",
    description: "iOS va Android tizimlari uchun chiroyli UI va tezkor backend integratsiyali mobil ilova.",
    price: 7500000,
    currency: "UZS",
    deliveryDays: 14,
    category: "dasturlash",
    images: [
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format&fit=crop&q=80",
    ],
    fields: {
      framework: "Flutter 3",
      platforms: "iOS & Android",
    },
    status: "active",
    createdAt: "2026-02-20T11:20:00.000Z",
  },
  {
    id: "svc-6",
    sellerId: "u-6",
    title: "Sayt va Landing Page uchun SEO Kopirayting",
    description: "Google va Yandex qidiruv tizimlarida yuqori o'rinlarga chiqish uchun professional SEO matnlar.",
    price: 900000,
    currency: "UZS",
    deliveryDays: 2,
    category: "kontent",
    images: [
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80",
    ],
    fields: {
      words: "2000 so'z",
      seo: "Kalit so'zlar bilan",
    },
    status: "active",
    createdAt: "2026-02-25T16:00:00.000Z",
  },
];

export const seedJobs: Job[] = [
  {
    id: "job-1",
    buyerId: "u-b1",
    buyerName: "TechCorp Tashkent MChJ",
    buyerRating: 4.9,
    title: "E-Commerce veb-saytini qayta dizayn qilish va Next.js ga o'tkazish",
    description: "Mavjud online do'konimizni zamonaviy UI/UX asosida yangilash va tezkor Next.js frontendiga o'tkazish talab etiladi.",
    category: "dasturlash",
    budgetMin: 6000000,
    budgetMax: 8000000,
    currency: "UZS",
    skillsRequired: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    screeningQuestions: ["Avval e-commerce loyihasi bajarganmisiz?"],
    proposalsCount: 4,
    postedAt: "2026-03-01T10:00:00.000Z",
    status: "ochiq",
  },
  {
    id: "job-2",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios",
    buyerRating: 5.0,
    title: "Logistika kompaniyasi uchun brendbuk va korporativ uslub",
    description: "Kompaniyamiz avtoparki, hujjatlar blankalari va ofis uchun to'liq vizual uslub kerak.",
    category: "dizayn",
    budgetMin: 3500000,
    budgetMax: 4500000,
    currency: "UZS",
    skillsRequired: ["Brandbook", "Logotip", "Figma", "Illustrator"],
    screeningQuestions: [],
    proposalsCount: 2,
    postedAt: "2026-03-05T12:00:00.000Z",
    status: "ochiq",
  },
  {
    id: "job-3",
    buyerId: "u-b3",
    buyerName: "Zamona Logistics",
    buyerRating: 4.8,
    title: "Omborxona qoldiqlarini boshqaruvchi Telegram Bot",
    description: "Omborga tovar kelishi va ketishini hisobga oluvchi, Excel formatida hisobot beruvchi bot kerak.",
    category: "dasturlash",
    budgetMin: 2000000,
    budgetMax: 2500000,
    currency: "UZS",
    skillsRequired: ["Python", "Telegram Bot", "PostgreSQL"],
    screeningQuestions: [],
    proposalsCount: 3,
    postedAt: "2026-03-10T15:00:00.000Z",
    status: "yopilgan",
  },
];

export const seedProposals: Proposal[] = [
  {
    id: "prop-1",
    jobId: "job-1",
    sellerId: "u-1",
    bidAmount: 7500000,
    coverLetter: "Assalomu alaykum. E-commerce bo'yicha katta tajribam bor. Next.js va Tailwind'da tezkor do'kon yaratib bera olaman.",
    screeningAnswers: [{ question: "Avval e-commerce loyihasi bajarganmisiz?", answer: "Ha, 3 ta yirik do'kon yaratganman." }],
    attachedImages: [],
    status: "yollandi",
    createdAt: "2026-03-02T11:00:00.000Z",
  },
  {
    id: "prop-2",
    jobId: "job-2",
    sellerId: "u-2",
    bidAmount: 4000000,
    coverLetter: "Assalomu alaykum. Logistika va B2B brending loyihalarida tajribam bor. 3 xil konseptsiya taqdim etaman.",
    screeningAnswers: [],
    attachedImages: [],
    status: "korib_chiqilmoqda",
    createdAt: "2026-03-06T14:00:00.000Z",
  },
];

export const seedContracts: Contract[] = [
  {
    id: "cnt-1",
    title: "E-Commerce veb-saytini qayta dizayn qilish va Next.js ga o'tkazish",
    buyerId: "u-b1",
    buyerName: "TechCorp Tashkent MChJ",
    sellerId: "u-1",
    sellerName: "Rustam Qosimov",
    sourceType: "taklif",
    jobId: "job-1",
    totalAmount: 7500000,
    status: "faol",
    createdAt: "2026-03-03T10:00:00.000Z",
  },
  {
    id: "cnt-2",
    title: "Mukammal Logotip va Brandbook dizayni",
    buyerId: "u-b2",
    buyerName: "ArtSoft Studios",
    sellerId: "u-2",
    sellerName: "Nigora Karimova",
    sourceType: "xizmat",
    serviceId: "svc-2",
    totalAmount: 2000000,
    status: "yakunlangan",
    createdAt: "2026-02-10T11:00:00.000Z",
  },
  {
    id: "cnt-3",
    title: "Biznes uchun Telegram CRM va To'lovli Bot",
    buyerId: "u-b3",
    buyerName: "Zamona Logistics",
    sellerId: "u-3",
    sellerName: "Jasur Bekchanov",
    sourceType: "xizmat",
    serviceId: "svc-3",
    totalAmount: 1800000,
    status: "nizo",
    createdAt: "2026-02-18T14:00:00.000Z",
  },
  {
    id: "cnt-4",
    title: "Cross-platform Flutter mobil ilova yaratish",
    buyerId: "u-b5",
    buyerName: "Apex Retail Group",
    sellerId: "u-5",
    sellerName: "Umid Aliyev",
    sourceType: "xizmat",
    serviceId: "svc-5",
    totalAmount: 7500000,
    status: "faol",
    createdAt: "2026-03-12T16:00:00.000Z",
  },
];

export const seedMilestones: Milestone[] = [
  {
    id: "ms-1-1",
    contractId: "cnt-1",
    title: "1-Bosqich: Figma Dizayn va Prototip",
    description: "To'liq UI/UX dizayn va interaktiv prototip topshirish",
    amount: 3500000,
    status: "qabul_qilindi",
    dueDate: "2026-03-05T00:00:00.000Z",
    submittedAt: "2026-03-05T16:00:00.000Z",
    approvedAt: "2026-03-05T17:00:00.000Z",
  },
  {
    id: "ms-1-2",
    contractId: "cnt-1",
    title: "2-Bosqich: Next.js Frontend Dasturlash",
    description: "Responsive veb-ilova va API integratsiyasi",
    amount: 4000000,
    status: "mablaglangan",
    dueDate: "2026-03-20T00:00:00.000Z",
  },
  {
    id: "ms-2-1",
    contractId: "cnt-2",
    title: "Logotip va Brandbook yakuniy topshirish",
    description: "3 ta konseptsiya va vektor fayllar",
    amount: 2000000,
    status: "qabul_qilindi",
    dueDate: "2026-02-15T00:00:00.000Z",
    submittedAt: "2026-02-14T14:00:00.000Z",
    approvedAt: "2026-02-15T10:00:00.000Z",
  },
  {
    id: "ms-3-1",
    contractId: "cnt-3",
    title: "Telegram Bot to'liq funksional",
    description: "Bot dasturlash va to'lovlar integratsiyasi",
    amount: 1800000,
    status: "topshirildi",
    dueDate: "2026-02-28T00:00:00.000Z",
    submittedAt: "2026-02-28T18:00:00.000Z",
  },
  {
    id: "ms-4-1",
    contractId: "cnt-4",
    title: "Mobil ilova MVP topshirish",
    description: "iOS va Android uchun dastlabki versiya",
    amount: 7500000,
    status: "topshirildi",
    dueDate: "2026-04-10T00:00:00.000Z",
    submittedAt: "2026-04-10T15:00:00.000Z",
  },
];

export const seedMessages: Message[] = [
  {
    id: "msg-1",
    contractId: "cnt-1",
    senderId: "u-b1",
    text: "Salom Rustam! Figma maketlarini kutib qolamiz.",
    createdAt: "2026-03-03T10:30:00.000Z",
  },
  {
    id: "msg-2",
    contractId: "cnt-1",
    senderId: "u-1",
    text: "Salom! Figma maketlari tayyor bo'ldi, havola: figma.com/file/xyz",
    createdAt: "2026-03-05T16:00:00.000Z",
  },
];

export const seedOfferMessages: Message[] = [];
export const seedOffers: Offer[] = [];

export const seedReviews: Review[] = [
  {
    id: "rev-1",
    contractId: "cnt-2",
    buyerName: "ArtSoft Studios",
    sellerId: "u-2",
    rating: 5,
    comment: "Ajoyib ish! Nigora juda kreativ va belgilangan muddatdan oldin logotipni taqdim etdi. Tavsiya qilaman!",
    createdAt: "2026-02-15T10:00:00.000Z",
  },
];

export const seedNotifications: AppNotification[] = [];

