/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LivenessDto: {
            /** @example ok */
            status: string;
            /** @example 42 */
            uptimeSeconds: number;
        };
        ReadinessDto: {
            /** @example ok */
            status: string;
            /** @example true */
            db: boolean;
            /** @example true */
            redis: boolean;
        };
        ApiErrorDto: {
            /**
             * @description Taksonomiya kodi (`error-codes.ts`). Frontend shu bo’yicha matn tanlaydi.
             * @example VALIDATION
             */
            code: string;
            /**
             * @description Log/debug uchun — foydalanuvchiga ko’rsatilmaydi.
             * @example Validatsiya muvaffaqiyatsiz
             */
            message?: string;
            /**
             * @description Maydon-darajali validatsiya — to’g’ridan-to’g’ri forma maydonlariga.
             * @example {
             *       "phone": "Raqam band"
             *     }
             */
            fieldErrors?: {
                [key: string]: string;
            };
            /**
             * @description So’rov identifikatori — log bilan bog’lash uchun (`x-request-id`).
             * @example 3f9a1c2e-...
             */
            requestId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessDto"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
}
